### ISSUE TITLE
Infusion Crafting Crash

### ISSUE THREAD

**Issue by Quagga22** [Azanor/thaumcraft#1473]
I tried to make the Everfull Urn from Thaumic Exploration and when I used my wand on the Infusion Matrix my game crashed.  I removed all the mods and added a few at a time to see if any of them caused the game to crash when replicating the crafting.  Nothing caused it to crash again.  I did this in a new instance, but when I went back to my old one and made a new world, the game crashed from trying to do the infusion.  I have been trying to get this to work for a few hours now and still have had no luck.  Below is the crash I was getting.  If you need more of my log let me know.  Please help, because I just want to play again. :)

Time: 1/4/15 5:16 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at thaumcraft.api.crafting.InfusionRecipe.matches(InfusionRecipe.java:43)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.findMatchingInfusionRecipe(ThaumcraftCraftingManager.java:245)
	at thaumcraft.common.tiles.TileInfusionMatrix.craftingStart(TileInfusionMatrix.java:284)
	at thaumcraft.common.tiles.TileInfusionMatrix.onWandRightClick(TileInfusionMatrix.java:714)
	at thaumcraft.common.items.wands.ItemWandCasting.onItemUseFirst(ItemWandCasting.java:377)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:360)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at thaumcraft.api.crafting.InfusionRecipe.matches(InfusionRecipe.java:43)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.findMatchingInfusionRecipe(ThaumcraftCraftingManager.java:245)
	at thaumcraft.common.tiles.TileInfusionMatrix.craftingStart(TileInfusionMatrix.java:284)
	at thaumcraft.common.tiles.TileInfusionMatrix.onWandRightClick(TileInfusionMatrix.java:714)
	at thaumcraft.common.items.wands.ItemWandCasting.onItemUseFirst(ItemWandCasting.java:377)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:360)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1b9f7fb1
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Quagga22** [comment]
So I found out it's something from Forbidden Magic that is causing the crash.
