### ISSUE TITLE
Thaumcraft-1.7.10-4.2.3.3 crash

### ISSUE THREAD

**Issue by oks1998** [Azanor/thaumcraft#1546]
java.lang.ArrayIndexOutOfBoundsException: 12

    at thaumcraft.common.blocks.BlockCustomPlantItem.func_77617_a(BlockCustomPlantItem.java:46)
    at net.minecraft.item.Item.func_77650_f(Item.java:440)
    at net.minecraft.item.ItemStack.func_77954_c(ItemStack.java:117)
    at net.minecraft.client.renderer.entity.RenderItem.func_76986_a(RenderItem.java:203)
    at net.minecraft.client.renderer.entity.RenderItem.func_76986_a(RenderItem.java:746)
    at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:293)
    at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:271)
    at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:244)
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:712)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1552)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1302)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
    at java.lang.reflect.Method.invoke(-1)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

world cannot start again, need use mcedit to move the player to others place

**Comment by MalkContent** [comment]
full log pls, for mod list

**Comment by oks1998** [comment]
http://openeye.openmods.info/crashes/9c4336c3db1f840f88afa32183471260

crash report file deleted =-=, left this website can see only

**Comment by MalkContent** [comment]
Hey look, a giant ass mod list \^\^ i never would have guessed. can you copy the map to local, see if it crashes, too and then uninstall every mod but tc? y,know, to find out if it's really a tc thing.

**Comment by oks1998** [comment]
but i already change my player to others place, and start the map already....the crash happen when i going to somewhere to find witch, and suddenly saw a block look like this texture :http://i.imgur.com/eRvnj0M.png

and then crash =-=

**Comment by MalkContent** [comment]
since all tc plants seem to work fine on my end, my guess is that another mod messes with tc here. back up your world and try and uninstall every mod besides tc. if it doesn't crash anymore, reinstall the mods one by one and see when it crashes so we know the culprit.

**Comment by Azanor** [comment]
Yup, it looks like something else is trying to render a TC plant that doesn't actually exist.
