### ISSUE TITLE
Nitor causing crash

### ISSUE THREAD

**Issue by WolfAmaril** [Azanor/thaumcraft#1559]
Whenever I try to load a SSP world/start a new SSP world, I get the following.

http://pastebin.com/N4Pc7MdJ

I will be posting this to the Bibliocraft Issue tracker as well

**Comment by MalkContent** [comment]
could you try that with only tc and bibliocraft installed?

**Comment by Azanor** [comment]
This looks like a classic item/block id conflict situation.

**Comment by WolfAmaril** [comment]
I thought those were all supposed to have been fixed with the update to 1.7

**Comment by Azanor** [comment]
They can and do still happen unfortunately.

**Comment by twothe** [comment]
I am not sure if this is a conflict. I have a similar issue during world start, but only with my creative world. However I never placed neither Nitor nor a hungry chest.

    java.lang.ClassCastException: thaumcraft.common.tiles.TileNitor cannot be cast to thaumcraft.common.tiles.TileChestHungry
	at thaumcraft.common.blocks.BlockChestHungry.func_149670_a(BlockChestHungry.java:160)
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:870)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:803)
	at thaumcraft.client.fx.particles.FXWisp.func_70071_h_(FXWisp.java:204)
	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:166)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_70_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1575)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by twothe** [comment]
Seems to happen only if I switch from multiplayer to a single player world without restarting the client in between.

**Comment by Azanor** [comment]
Hmmm, I suspect the block id's might be different between your single player world and the server you are connecting to. That in itself is perfectly normal, but I wonder why it would be confusing something in my mod. I will have to take a look.
