### ISSUE TITLE
Cauldron+ Thaumcraft 4.2.3.4

### ISSUE THREAD

**Issue by RNS60** [Azanor/thaumcraft#1571]
Hi! I'm using the latest and clean version of cauldron 1.7.10 server and Thaumcraft 4.2.3.4, but every time on starting it, i have this error:
[17:34:27] [Server thread/ERROR]: The mod Thaumcraft (Thaumcraft) requires mod versions [Forge@[10.13.2,)] to be available
[17:34:27] [Server thread/ERROR]: Encountered an unexpected exception
cpw.mods.fml.common.MissingModsException
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:244) ~[Loader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:472) ~[Loader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) ~[FMLServerHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:317) ~[FMLCommonHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.187]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:170) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]

Please, give me an advise how i can to resolve this error.
Sorry for my bad english, i am from Ukraine :)

**Comment by MalkContent** [comment]
Cauldron's not officially supported.
Anyways, I would forward this to cauldron. If cauldron requires forge installed (I have no idea about cauldron), you should update your forge, since it doesn't meet the version requirement.

**Comment by RNS60** [comment]
Thanks for your answer!

Our team rebuilded the cauldron's core using the latest Forge for 1.7.10 and the problem was resolved.

It's really just a problem of cauldron's core.
