### ISSUE TITLE
 java.lang.NullPointerException server log spam

### ISSUE THREAD

**Issue by pansx** [Azanor/thaumcraft#1587]
lots of this:
[08:12:27 WARN]: java.lang.NullPointerException
[08:12:27 WARN]:        at thaumcraft.common.blocks.BlockWarded.getBlock(BlockWarded.java:109)
[08:12:27 WARN]:        at thaumcraft.common.blocks.BlockWarded.isLadder(BlockWarded.java:264)
[08:12:27 WARN]:        at CoroUtil.pathfinding.PFQueue.findPathOptions(PFQueue.java:1227)
[08:12:27 WARN]:        at CoroUtil.pathfinding.PFQueue.addToPath(PFQueue.java:1078)
[08:12:27 WARN]:        at CoroUtil.pathfinding.PFQueue.createPathTo(PFQueue.java:952)
[08:12:27 WARN]:        at CoroUtil.pathfinding.PFQueue.manageQueue(PFQueue.java:292)
[08:12:27 WARN]:        at CoroUtil.pathfinding.PFQueue.run(PFQueue.java:160)
[08:12:27 WARN]:        at java.lang.Thread.run(Thread.java:745)
Thaumcraft-1.7.10-4.2.3.4 & ZombieAwareness-1.9.6 & coroutil-1.1.2 installed
forge 1236

**Comment by shobu9** [comment]
#890 i doudgth he can do something about it ..

**Comment by Azanor** [comment]
That bug is actually triggered by CoroUtil (whatever that is).

**Comment by the-ible** [comment]
Utility library used by Coros mods
http://coros.us/mods/
