### ISSUE TITLE
ThermalExpansion integration problem

### ISSUE THREAD

**Issue by jamesjer** [Azanor/thaumcraft#1609]
With Thaumcraft 4.2.3.4 and ThermalExpansion 4.0.0B8-23, I am seeing this (non-fatal) exception on my server at startup.  I can provide more information if needed.

[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getAspectsFromIngredients(ThaumcraftCraftingManager.java:861)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCraftingRecipes(ThaumcraftCraftingManager.java:833)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:903)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getAspectsFromIngredients(ThaumcraftCraftingManager.java:854)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCraftingRecipes(ThaumcraftCraftingManager.java:833)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:903)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getObjectTags(ThaumcraftCraftingManager.java:313)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thaumcraft.common.lib.InternalMethodHandler.getObjectAspects(InternalMethodHandler.java:46)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thaumcraft.api.ThaumcraftApiHelper.getObjectAspects(ThaumcraftApiHelper.java:95)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thaumcraft.api.aspects.AspectList.<init>(AspectList.java:22)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.GeneratedConstructorAccessor56.newInstance(Unknown Source)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cofh.api.modhelpers.ThaumcraftHelper.parseAspects(ThaumcraftHelper.java:93)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cofh.api.modhelpers.ThaumcraftHelper.parseAspects(ThaumcraftHelper.java:110)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thermalexpansion.plugins.tc4.TCPlugin.postInit(TCPlugin.java:149)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.reflect.Method.invoke(Method.java:483)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thermalexpansion.plugins.TEPlugins$Plugin.postInit(TEPlugins.java:49)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thermalexpansion.plugins.TEPlugins.postInit(TEPlugins.java:100)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at thermalexpansion.ThermalExpansion.postInit(ThermalExpansion.java:166)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.reflect.Method.invoke(Method.java:483)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.reflect.Method.invoke(Method.java:483)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at java.lang.reflect.Method.invoke(Method.java:483)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[19:27:09] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Azanor** [comment]
Hmmm, somehow aspects are being calculated for a recipe that contains null items. There is a known issue in TE that is messing with my aspect calculations. They are aware of it and are planning a fix, though I am not sure if they have done it yet.

**Comment by jamesjer** [comment]
After updating to the latest ThermalExpansion, this issue went away.  I'm going to close this as fixed.
