### ISSUE TITLE
Crashing on world-load, random items from other mods "cannot be cast to thaumcraft.api.wands.ItemFocusBasic"

### ISSUE THREAD

**Issue by Jaitsu** [Azanor/thaumcraft#1616]
I've been having this crash for weeks and I'd been blaming the other mod named in the crash (Bibliocraft), but now it seems Aether is having the same issue with the same call in Thaumcraft. It seems to have something to do with wand foci, but it happens on world-load even for brand new saves where I don't even have a wand, as well as sometimes when connecting to servers.

java.lang.ClassCastException: net.aetherteam.aether.items.ItemAccessory cannot be cast to thaumcraft.api.wands.ItemFocusBasic
	at thaumcraft.common.items.wands.ItemWandCasting.getFocus(ItemWandCasting.java:433)
	at thaumcraft.client.renderers.models.gear.ModelWand.render(ModelWand.java:136)
	at thaumcraft.client.renderers.item.ItemWandRenderer.renderItem(ItemWandRenderer.java:133)
	at net.minecraftforge.client.ForgeHooksClient.renderEquippedItem(ForgeHooksClient.java:220)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:80)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:499)
	at shadersmodcore.client.ShadersRender.renderItemFP(ShadersRender.java:86)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:954)
	at shadersmodcore.client.ShadersRender.renderHand0(ShadersRender.java:57)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1625)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Azanor** [comment]
This sort of thing happens if there is a mismatch between item id's on a client and on a server. Make sure you have the same mods on both and that they are the same versions.

**Comment by Jaitsu** [comment]
They do, yes - and this can happen without even connecting to a server, if I have two SP saves and switch from one to the other.

**Comment by Jaitsu** [comment]
After doing some research, you're right, though; I checked and the numeric IDs do indeed differ between the server and SP (for instance, the Portable Hole wand focus is 4409 when I connect to the server, and 4694 on the client)

I suspect this has something to do with the item IDs being stored differently from save to save as new mods are added? If I make two brand-new saves, I can't make it happen, but if I switch between an old save (one from before adding some mods) and a new one, there it goes. I'm not sure why, but in every one of these cases, it always seems to be a ClassCastException between a Thaumcraft item class (almost always ItemWandFocusBasic) and some other mod item class.
