### ISSUE TITLE
Crash when creating ichor using Thaumcraft 4.2.3.5, minecraft 1.7.10, and forge 10.13.2.1291

### ISSUE THREAD

**Issue by levicc00123** [Azanor/thaumcraft#1631]
a full crash log can be found [here](https://gist.github.com/levicc00123/dba9bbc1f605ee5ca832)

**Comment by OJwithC** [comment]
Ichor is from Thaumic Tinkerer.

**Comment by levicc00123** [comment]
I know that, but if you would've read my crash report, you would have seen a couple of lines that looks something like this.

at net.minecraftforge.fluids.BlockFluidFinite.func_149674_a(BlockFluidFinite.java:64)
**at thaumcraft.common.blocks.BlockFluxGas.func_149674_a(BlockFluxGas.java:93)**
at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:550)

The bolded line is what prompted me to report the bug here.
