### ISSUE TITLE
Total Game Crash

### ISSUE THREAD

**Issue by ShinysMindPalace** [Azanor/thaumcraft#1666]
I have several mods installed, namely Thaumcraft (from 1.7.2 i think - bug is preventing me from accessing it atm) Railcraft, Buildcraft, and Galaticraft. I was attempting to get a straw golem with the empty core to remove items from a minecart with a chest by indicating the holding rail i had stopped it on. After a few seconds of the golem looking at me, the game crashed, and I can get to a second of main menu before it spits out this crash report. 

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 3/9/15 4:33 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at uristqwerty.CraftGuide.client.fml.CraftGuideClient_FML.checkKeybind(CraftGuideClient_FML.java:37)
	at uristqwerty.CraftGuide.CraftGuide_FML$KeyCheckTick.clientTick(CraftGuide_FML.java:36)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_14_KeyCheckTick_clientTick_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1575)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 170329256 bytes (162 MB) / 440475648 bytes (420 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 19 mods loaded, 19 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CodeChickenCore{1.0.2.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	NotEnoughItems{1.0.2.15} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Core{6.0.18} [BuildCraft] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Builders{6.0.18} [BC Builders] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Energy{6.0.18} [BC Energy] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Factory{6.0.18} [BC Factory] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Transport{6.0.18} [BC Transport] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BuildCraft|Silicon{6.0.18} [BC Silicon] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftCore{3.0.8} [Galacticraft Core] (GalacticraftCore-1.7-3.0.8.271.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	GalacticraftMars{3.0.8} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.8.271.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Baubles{1.0.1.7} [Baubles] (Baubles-1.7.10-1.0.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Thaumcraft{4.2.0.1} [Thaumcraft] (Thaumcraft-1.7.10-4.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Railcraft{9.3.1.0} [Railcraft] (Railcraft_1.7.10-9.3.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TwilightForest{2.2.3} [The Twilight Forest] (twilightforest-1.7.2-2.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.52, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ShinysMindPalace** [comment]
however, new crash on the same world wherein this originally occurred 

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 3/10/15 2:50 AM
Description: Updating screen events

java.lang.NoSuchMethodError: cpw.mods.fml.common.registry.GameData.buildItemDataList()Ljava/util/Map;
	at thaumcraft.client.gui.GuiResearchRecipe.<init>(GuiResearchRecipe.java:114)
	at thaumcraft.client.gui.GuiResearchBrowser.func_73864_a(GuiResearchBrowser.java:893)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at thaumcraft.client.gui.GuiResearchRecipe.<init>(GuiResearchRecipe.java:114)
	at thaumcraft.client.gui.GuiResearchBrowser.func_73864_a(GuiResearchBrowser.java:893)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: thaumcraft.client.gui.GuiResearchBrowser

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['JojoMojoMonster'/639, l='MpServer', x=232.12, y=68.62, z=366.94]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (236,64,256), Chunk: (at 12,4,0 in 14,16; contains blocks 224,0,256 to 239,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1951700 game time, 21359 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 116 total; [EntityBlock['unknown'/17409, l='MpServer', x=294.25, y=105.00, z=209.25], EntitySheep['Sheep'/1886721, l='MpServer', x=245.47, y=65.00, z=389.47], EntityMooshroom['Mooshroom'/1861180, l='MpServer', x=246.84, y=65.00, z=380.47], EntityItem['item.item.egg'/1890876, l='MpServer', x=212.22, y=60.13, z=335.69], EntityEnderman['Enderman'/1900088, l='MpServer', x=229.63, y=14.00, z=366.50], EntitySkeleton['Skeleton'/1901625, l='MpServer', x=182.50, y=41.00, z=430.50], EntityEnderman['Enderman'/1900089, l='MpServer', x=232.59, y=13.00, z=368.00], EntityZombie['Zombie'/1901624, l='MpServer', x=184.50, y=41.00, z=430.50], EntitySkeleton['Skeleton'/1901626, l='MpServer', x=179.50, y=41.00, z=431.50], EntityZombie['Zombie'/1901623, l='MpServer', x=183.50, y=41.00, z=431.50], EntityMooshroom['Mooshroom'/38451, l='MpServer', x=248.31, y=65.00, z=383.72], EntityGolemBase['Thaumium Golem'/1881636, l='MpServer', x=243.91, y=68.00, z=373.47], EntityBlock['unknown'/4665, l='MpServer', x=333.25, y=106.00, z=198.25], EntityHorse['Horse'/1854558, l='MpServer', x=302.13, y=69.00, z=431.50], EntityPig['Pig'/1879640, l='MpServer', x=245.88, y=65.00, z=385.07], EntityChicken['Chicken'/1854546, l='MpServer', x=300.41, y=68.00, z=396.06], EntityMooshroom['Mooshroom'/1891405, l='MpServer', x=244.34, y=65.00, z=381.72], EntityMooshroom['Mooshroom'/1879111, l='MpServer', x=245.47, y=65.00, z=381.14], EntitySheep['Sheep'/1900664, l='MpServer', x=245.71, y=65.00, z=387.46], EntityItem['item.item.egg'/1897570, l='MpServer', x=204.06, y=65.13, z=353.44], EntityChicken['Chicken'/128, l='MpServer', x=156.53, y=63.00, z=291.56], EntityChicken['Chicken'/129, l='MpServer', x=163.41, y=63.00, z=303.41], EntityItem['item.item.egg'/1896094, l='MpServer', x=252.88, y=63.13, z=307.53], EntityChicken['Chicken'/132, l='MpServer', x=159.47, y=62.41, z=313.19], EntityChicken['Chicken'/134, l='MpServer', x=157.69, y=62.69, z=311.63], EntityChicken['Chicken'/152, l='MpServer', x=167.41, y=62.27, z=298.38], EntityChicken['Chicken'/154, l='MpServer', x=166.19, y=62.52, z=305.22], EntityPig['Pig'/1893052, l='MpServer', x=246.60, y=65.00, z=386.53], EntityChicken['Chicken'/172, l='MpServer', x=187.53, y=65.00, z=317.47], EntityChicken['Chicken'/173, l='MpServer', x=192.47, y=65.00, z=314.53], EntityChicken['Chicken'/175, l='MpServer', x=185.63, y=63.00, z=347.44], EntityHorse['Horse'/176, l='MpServer', x=177.19, y=63.00, z=367.47], GCEntityClientPlayerMP['JojoMojoMonster'/639, l='MpServer', x=232.12, y=68.62, z=366.94], EntityHorse['Horse'/177, l='MpServer', x=182.28, y=63.00, z=361.06], EntityHorse['Horse'/178, l='MpServer', x=171.97, y=63.00, z=372.78], EntityChicken['Chicken'/185, l='MpServer', x=213.44, y=61.38, z=336.56], EntityChicken['Chicken'/187, l='MpServer', x=203.44, y=65.00, z=351.56], EntityMooshroom['Mooshroom'/167103, l='MpServer', x=243.82, y=65.00, z=380.45], EntityChicken['Chicken'/203, l='MpServer', x=215.59, y=62.45, z=293.47], EntityItem['item.item.egg'/1891536, l='MpServer', x=192.16, y=65.13, z=315.28], EntityChicken['Chicken'/205, l='MpServer', x=210.53, y=64.00, z=326.47], EntityChicken['Chicken'/206, l='MpServer', x=221.53, y=64.45, z=357.53], EntityChicken['Chicken'/207, l='MpServer', x=265.44, y=68.00, z=347.59], EntityPig['Pig'/19165, l='MpServer', x=225.91, y=63.00, z=431.69], EntityChicken['Chicken'/241, l='MpServer', x=217.63, y=65.00, z=324.41], EntityChicken['Chicken'/242, l='MpServer', x=232.59, y=64.00, z=314.63], EntityGolemBase['Thaumium Golem'/243, l='MpServer', x=245.28, y=67.00, z=362.16], EntityPig['Pig'/837874, l='MpServer', x=246.31, y=65.00, z=383.72], EntityBlock['unknown'/4863, l='MpServer', x=294.25, y=105.00, z=209.25], EntityItem['item.item.egg'/1897241, l='MpServer', x=211.25, y=64.13, z=325.41], EntityChicken['Chicken'/268, l='MpServer', x=246.66, y=63.00, z=304.53], EntityChicken['Chicken'/270, l='MpServer', x=253.47, y=63.00, z=305.56], EntityChicken['Chicken'/271, l='MpServer', x=251.59, y=64.00, z=331.53], EntityGolemBase['Straw Golem'/273, l='MpServer', x=246.38, y=67.00, z=364.50], EntityGolemBase['Straw Golem'/274, l='MpServer', x=248.50, y=67.00, z=364.72], EntityGolemBase['Straw Golem'/275, l='MpServer', x=244.53, y=67.00, z=366.78], EntityGolemBase['Straw Golem'/276, l='MpServer', x=243.44, y=67.00, z=365.44], EntityGolemBase['Straw Golem'/277, l='MpServer', x=247.59, y=67.00, z=365.59], EntityGolemBase['Straw Golem'/279, l='MpServer', x=243.97, y=67.00, z=356.31], EntityPig['Pig'/1862912, l='MpServer', x=245.22, y=65.00, z=385.13], EntityChicken['Chicken'/312, l='MpServer', x=247.84, y=65.00, z=373.77], EntityChicken['Chicken'/313, l='MpServer', x=249.14, y=65.00, z=373.74], EntityChicken['Chicken'/314, l='MpServer', x=249.25, y=65.00, z=374.17], EntityChicken['Chicken'/315, l='MpServer', x=247.06, y=65.00, z=372.99], EntityChicken['Chicken'/316, l='MpServer', x=248.89, y=65.00, z=375.85], EntityBlock['unknown'/4925, l='MpServer', x=333.25, y=106.00, z=198.25], EntityChicken['Chicken'/317, l='MpServer', x=247.06, y=65.00, z=374.83], EntityChicken['Chicken'/318, l='MpServer', x=247.70, y=65.00, z=375.20], EntityChicken['Chicken'/319, l='MpServer', x=249.85, y=65.00, z=374.61], EntityChicken['Chicken'/320, l='MpServer', x=248.34, y=64.63, z=375.84], EntityChicken['Chicken'/321, l='MpServer', x=249.85, y=65.00, z=376.00], EntityChicken['Chicken'/322, l='MpServer', x=247.16, y=65.00, z=374.28], EntityChicken['Chicken'/323, l='MpServer', x=247.85, y=65.00, z=373.09], EntityChicken['Chicken'/324, l='MpServer', x=249.34, y=65.00, z=375.85], EntityChicken['Chicken'/325, l='MpServer', x=249.22, y=65.00, z=373.15], EntityChicken['Chicken'/326, l='MpServer', x=247.74, y=65.00, z=374.74], EntityChicken['Chicken'/327, l='MpServer', x=249.83, y=65.00, z=374.08], EntityChicken['Chicken'/328, l='MpServer', x=249.25, y=64.63, z=375.28], EntityChicken['Chicken'/329, l='MpServer', x=247.79, y=65.00, z=375.85], EntityChicken['Chicken'/330, l='MpServer', x=247.15, y=65.00, z=373.72], EntityChicken['Chicken'/331, l='MpServer', x=249.84, y=65.00, z=373.44], EntityChicken['Chicken'/332, l='MpServer', x=249.29, y=65.00, z=374.74], EntityChicken['Chicken'/333, l='MpServer', x=249.79, y=65.00, z=375.21], EntityGolemBase['Straw Golem'/334, l='MpServer', x=244.53, y=67.00, z=370.44], EntityChicken['Chicken'/336, l='MpServer', x=247.15, y=65.00, z=375.85], EntityChicken['Chicken'/338, l='MpServer', x=248.25, y=65.00, z=375.34], EntityChicken['Chicken'/341, l='MpServer', x=248.63, y=65.00, z=373.25], EntityMinecartChest['entity.MinecartChest.name'/40281, l='MpServer', x=189.75, y=58.34, z=402.56], EntityMinecartChest['entity.MinecartChest.name'/28510, l='MpServer', x=188.50, y=58.34, z=402.50], EntityChicken['Chicken'/367, l='MpServer', x=260.22, y=63.00, z=305.28], EntityChicken['Chicken'/16771, l='MpServer', x=245.34, y=65.00, z=385.78], EntityChicken['Chicken'/16772, l='MpServer', x=248.47, y=65.00, z=380.50], EntityGolemBase['Thaumium Golem'/16773, l='MpServer', x=246.50, y=65.00, z=395.38], EntityGolemBase['Thaumium Golem'/16778, l='MpServer', x=246.50, y=64.63, z=394.53], EntityGolemBase['Straw Golem'/28559, l='MpServer', x=195.47, y=64.00, z=406.50], EntityBlock['unknown'/4497, l='MpServer', x=294.25, y=105.00, z=209.25], EntityHorse['Horse'/19859, l='MpServer', x=157.13, y=64.00, z=378.63], EntityHorse['Horse'/19860, l='MpServer', x=188.50, y=61.00, z=412.28], EntitySheep['Sheep'/1874824, l='MpServer', x=247.53, y=65.00, z=389.53], EntityCreeper['Creeper'/1887624, l='MpServer', x=218.04, y=64.00, z=355.34], EntityPig['Pig'/19863, l='MpServer', x=193.97, y=64.00, z=393.16], EntityChicken['Chicken'/407, l='MpServer', x=294.41, y=73.00, z=319.34], EntityChicken['Chicken'/408, l='MpServer', x=305.47, y=72.00, z=350.44], EntityHorse['Horse'/410, l='MpServer', x=297.63, y=69.00, z=381.09], EntityItem['item.item.egg'/1900960, l='MpServer', x=294.53, y=73.13, z=317.38], EntityItem['item.item.egg'/1899939, l='MpServer', x=232.97, y=64.13, z=315.78], EntityItem['item.item.egg'/1902047, l='MpServer', x=248.84, y=63.13, z=303.97], EntityItem['item.item.egg'/1892312, l='MpServer', x=188.59, y=65.13, z=317.75], EntityGolemBase['Thaumium Golem'/1883090, l='MpServer', x=244.22, y=68.00, z=371.22], EntityHorse['Horse'/1855946, l='MpServer', x=308.94, y=69.00, z=436.94], EntityLocomotiveElectric['Electric Locomotive'/473, l='MpServer', x=336.50, y=71.50, z=321.50], EntityCartBasic['entity.MinecartRideable.name'/474, l='MpServer', x=338.19, y=71.50, z=321.50], EntityCartChest['entity.MinecartChest.name'/478, l='MpServer', x=339.50, y=71.50, z=320.97], EntityMinecartChest['entity.MinecartChest.name'/40437, l='MpServer', x=191.19, y=58.50, z=402.66], EntityItem['item.item.egg'/1898986, l='MpServer', x=258.75, y=63.13, z=305.84], EntityPig['Pig'/404986, l='MpServer', x=244.78, y=65.00, z=384.03]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 206063584 bytes (196 MB) / 550154240 bytes (524 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 98
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 16 mods loaded, 16 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.2.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Core{6.0.18} [BuildCraft] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Builders{6.0.18} [BC Builders] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Energy{6.0.18} [BC Energy] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Factory{6.0.18} [BC Factory] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Transport{6.0.18} [BC Transport] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildCraft|Silicon{6.0.18} [BC Silicon] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{3.0.8} [Galacticraft Core] (GalacticraftCore-1.7-3.0.8.271.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{3.0.8} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.8.271.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.7} [Baubles] (Baubles-1.7.10-1.0.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.0.1} [Thaumcraft] (Thaumcraft-1.7.10-4.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Railcraft{9.3.1.0} [Railcraft] (Railcraft_1.7.10-9.3.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.52, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
