### ISSUE TITLE
Thaumcraft / Baubles not saving anithing in playerdata

### ISSUE THREAD

**Issue by COM8** [Azanor/thaumcraft#1715]
This is proubably because you can't create any files for my name on Windows (my ingamename is COM8). The followig files are the files I am missing:
COM8.baub
COM8.baubback
COM8.thaum
COM8.thaumback

Thaumcraft-Error-Message:
[19:24:01] [Server thread/ERROR] [THAUMCRAFT]: Could not save research file for player COM8

Baubles-Error-Message:
[19:24:01] [Server thread/ERROR] [Baubles]: Could not save baubles file for player COM8
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.io.FileNotFoundException: D:\Minecraft\COMCRAFT 4.0\saves\New World\playerdata\COM8.baub (Das System kann die angegebene Datei nicht finden)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.io.FileOutputStream.open(Native Method)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.io.FileOutputStream.<init>(Unknown Source)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.io.FileOutputStream.<init>(Unknown Source)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at baubles.common.lib.PlayerHandler.savePlayerBaubles(PlayerHandler.java:106)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at baubles.common.event.EventHandlerEntity.playerSave(EventHandlerEntity.java:99)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_181_EventHandlerEntity_playerSave_SaveToFile.invoke(.dynamic)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.event.ForgeEventFactory.firePlayerSavingEvent(ForgeEventFactory.java:210)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.storage.SaveHandler.func_75753_a(SaveHandler.java:257)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.management.ServerConfigurationManager.func_72391_b(ServerConfigurationManager.java:273)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedPlayerList.func_72391_b(SourceFile:26)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.management.ServerConfigurationManager.func_72389_g(ServerConfigurationManager.java:886)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:105)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[19:24:01] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by COM8** [comment]
Minecraft 1.7.10
Forge 10.13.2.1291
Thaumcraft 4.2.3.5

**Comment by Azanor** [comment]
Hehe, that is a new one. Not sure what to do about it though

**Comment by Azanor** [comment]
I could probably just append something to the filename to get around that. It is probably the simplest solution. Obviously this will break all the things so this will only be implemented in the 1.8 version.

**Comment by tschallacka** [comment]
I would suggest not saving by username but by UUID. That way the namechanges wont affect players and golems and warded blocks will still work with players.
Its really annoying having to rename all the .baub and the thaum fiiles when a player changes his names.

**Comment by chrisbecke** [comment]
Why isn't the thaumcraft data being saved as a node in the player.dat again?

**Comment by TheMadmanofChaos** [comment]
I can see two reasons:: Ease of recovery should something happen, so an NBT editor isn't needed, and is more flexible then player NBT.

I remember a mod author mentioning how player NBT can't be accessed while a player isn't on a server. He might have made it as such as a "Just in case", future proofing for any ideas he might have. Same reason Blood magic stores soul network values in the world data instead of the player or an item.
