### ISSUE TITLE
Thaumcraft 4.2.3.5 Crash on Post-Initilisation (NullPointerException)

### ISSUE THREAD

**Issue by Amarnra** [Azanor/thaumcraft#1848]
I am by no means experienced in Java or crash log debugging, so forgive me if post-initilisation is not the correct term. Minecraft Forge reaches step 6/7 ("Finishing Up"), freezes and does not crash. There is no crashlog, however the forge client logs reveal that there is a null pointer exception. 

An excerpt being: 

[20:42:15] [Client thread/ERROR] [FML/]: The following problems were captured during this phase
[20:42:15] [Client thread/ERROR] [FML/]: Caught exception from Thaumcraft
java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77960_j(Unknown Source) ~[add.class:?]
	at thaumcraft.common.Thaumcraft.postInit(Thaumcraft.java:221) ~[Thaumcraft.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[modpack.jar:?]
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]

Downgrading to Java version 1.7.0_80 received the following error and produced a crash log:

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full log for the 1.8.0_51 crash may be found here:
http://www.mediafire.com/download/4qwb84s2y0ax5s4/Java_1.8.0_51_MC_1.7.10_Thaum_4.2.3.5.log

Full log for the 1.7.0_80 crash may be found here:
http://www.mediafire.com/download/be97vz8q47qbh7z/Java_1.7.0_80_MC_1.7.10_Thaum_4.2.3.5_Log.log

Full crash report for the 1.7.0_80 crash may be found here:
http://www.mediafire.com/view/xg1ru9e92vbxsqv/Java_1.7.0_80_MC_1.7.10_Thaum_4.2.3.5_Crash_Log.txt

 I have tried installing earlier versions of Thaumcraft to no avail.

**Comment by Amarnra** [comment]
In removing Pam's Harvest the Nether 1.7.10a the minecraft client is able to start, however it cannot join a forge server of the same pack or host a singleplayer game.

**Comment by evknucklehead** [comment]
I highly recommend getting in touch with the pack's authors or community to see if they have any experience with this bug before asking here. Chances are higher that they've seen this particular interaction and know how to fix it.

If you can determine that it is, for certain, caused by something in Thaumcraft, you'll likely have a better idea what exactly is wrong so Azanor will be able to fix it.

Also, in the future try uploading the content of the log files to Pastebin or paste.ubuntu.org instead of mediafire, as the first two sites do not require downloading the file to take a look at it.
